### ISSUE TITLE
Interface Inspector在Sierra下不能用？

### ISSUE THREAD

**Issue by aleonchen** [AloneMonkey/MacReverse#1]
提示出现“Could not attach to application”

**Comment by AloneMonkey** [comment]
可以用的。

> 当然这里还有坑，如何你发现attach process的时候报错的话，请参考[Fix Bug for Interface Inspector on macOS Serria](http://bbs.iosre.com/t/fix-bug-for-interface-inspector-on-macos-serria/5665)这篇文章重新编译mach_inject_bundle_stub.bundle。

这一步你做了吗？

**Comment by aleonchen** [comment]
@AloneMonkey 嗯，是的，的确可以用。重新编了下的确搞定了，其实你工程里面也有。感谢

**Comment by MustangYM** [comment]
你好, 貌似当前Mojave下, interface inspector怎么也破解不成功了...去掉第二步签名弹窗后, 就一直闪退, 网上的别的破解办法也是这个症状, 您的也是这个症状, 您能帮忙看下吗, 跪谢

**Comment by ksmokee** [comment]
MAC AIR 10.14.6
根据工程中的mach_inject_bundle_stub.bundle 替换 Frameworks后 点击软件在挂载的时候会闪退。

这似乎是新版系统与interface  不兼容或mach_inject_bundle_stub与10.14.6不兼容
